---
- name: ensure python development packages are at the latest version via apt
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - build-essential
    - python
    - python-dev
    - python-virtualenv
    - python-sphinx
    - pylint
    - virtualenvwrapper
