---
- name: ensure python development packages are at the latest version via yum
  yum:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - "@Development tools"
    - python
    - python-devel
    - python-virtualenv
    - python-pip
    - python-sphinx
    - python2-pylint

- name: ensure virtual env wrapper is installed
  pip:
    name: virtualenvwrapper
    state: latest
